In [1]:
# Install Pytorch & other libraries
%pip install "torch==2.4.1" tensorboard 
%pip install flash-attn "setuptools<71.0.0" scikit-learn 
 
# Install Hugging Face libraries
%pip install  --upgrade \
  "datasets==3.1.0" \
  "accelerate==1.2.1" \
  "hf-transfer==0.1.8"
  #"transformers==4.47.1" \
 
# ModernBERT is not yet available in an official release, so we need to install it from github
%pip install "git+https://github.com/huggingface/transformers.git@6e0515e99c39444caae39472ee1b2fd76ece32f1" --upgrade

Collecting torch==2.4.1
  Obtaining dependency information for torch==2.4.1 from https://files.pythonhosted.org/packages/cc/df/5204a13a7a973c23c7ade615bafb1a3112b5d0ec258d8390f078fa4ab0f7/torch-2.4.1-cp312-cp312-manylinux1_x86_64.whl.metadata
  Downloading torch-2.4.1-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
Collecting tensorboard
  Obtaining dependency information for tensorboard from https://files.pythonhosted.org/packages/5d/12/4f70e8e2ba0dbe72ea978429d8530b0333f0ed2140cc571a48802878ef99/tensorboard-2.19.0-py3-none-any.whl.metadata
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: filelock in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch==2.4.1) (3.12.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch==2.4.1) (4.8.0)
Collecting sympy (from torch==2.4.1)
  Obtaining dependency information for sympy from https://files.pythonhosted.org/packages/99/ff/c87e0622b1dadea79d2fb0b25ade9ed98954c9033722eb707053d310d4f3/sympy-1.13.3-py3-none-any.whl.metadata
  Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.4.1)
  Obtaining dependency information for networkx from https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch==2.4.1) (3.1.2)
Requirement already satisfied: fsspec in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch==2.4.1) (2023.9.2)
Requirement already satisfied: setuptools in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch==2.4.1) (68.0.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cuda-nvrtc-cu12==12.1.105 from https://files.pythonhosted.org/packages/b6/9f/c64c03f49d6fbc56196664d05dba14e3a561038a81a638eeb47f4d4cfd48/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cuda-runtime-cu12==12.1.105 from https://files.pythonhosted.org/packages/eb/d5/c68b1d2cdfcc59e72e8a5949a37ddb22ae6cade80cd4a57a84d4c8b55472/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cuda-cupti-cu12==12.1.105 from https://files.pythonhosted.org/packages/7e/00/6b218edd739ecfc60524e585ba8e6b00554dd908de2c9c66c1af3e44e18d/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cudnn-cu12==9.1.0.70 from https://files.pythonhosted.org/packages/9f/fd/713452cd72343f682b1c7b9321e23829f00b842ceaedcda96e742ea0b0b3/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cublas-cu12==12.1.3.1 from https://files.pythonhosted.org/packages/37/6d/121efd7382d5b0284239f4ab1fc1590d86d34ed4a4a2fdb13b30ca8e5740/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cufft-cu12==11.0.2.54 from https://files.pythonhosted.org/packages/86/94/eb540db023ce1d162e7bea9f8f5aa781d57c65aed513c33ee9a5123ead4d/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.4.1)
  Obtaining dependency information for nvidia-curand-cu12==10.3.2.106 from https://files.pythonhosted.org/packages/44/31/4890b1c9abc496303412947fc7dcea3d14861720642b49e8ceed89636705/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cusolver-cu12==11.4.5.107 from https://files.pythonhosted.org/packages/bc/1d/8de1e5c67099015c834315e333911273a8c6aaba78923dd1d1e25fc5f217/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.4.1)
  Obtaining dependency information for nvidia-cusparse-cu12==12.1.0.106 from https://files.pythonhosted.org/packages/65/5b/cfaeebf25cd9fdec14338ccb16f6b2c4c7fa9163aefcf057d86b9cc248bb/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.4.1)
  Obtaining dependency information for nvidia-nccl-cu12==2.20.5 from https://files.pythonhosted.org/packages/4b/2a/0a131f572aa09f741c30ccd45a8e56316e8be8dfc7bc19bf0ab7cfef7b19/nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata
  Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.4.1)
  Obtaining dependency information for nvidia-nvtx-cu12==12.1.105 from https://files.pythonhosted.org/packages/da/d3/8057f0587683ed2fcd4dbfbdfdfa807b9160b809976099d36b8f60d08f03/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.0.0 (from torch==2.4.1)
  Obtaining dependency information for triton==3.0.0 from https://files.pythonhosted.org/packages/fe/7b/7757205dee3628f75e7991021d15cd1bd0c9b044ca9affe99b50879fc0e1/triton-3.0.0-1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
  Downloading triton-3.0.0-1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch==2.4.1)
  Obtaining dependency information for nvidia-nvjitlink-cu12 from https://files.pythonhosted.org/packages/03/f8/9d85593582bd99b8d7c65634d2304780aefade049b2b94d96e44084be90b/nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata
  Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting absl-py>=0.4 (from tensorboard)
  Obtaining dependency information for absl-py>=0.4 from https://files.pythonhosted.org/packages/a2/ad/e0d3c824784ff121c03cc031f944bc7e139a8f1870ffd2845cc2dd76f6c4/absl_py-2.1.0-py3-none-any.whl.metadata
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting grpcio>=1.48.2 (from tensorboard)
  Obtaining dependency information for grpcio>=1.48.2 from https://files.pythonhosted.org/packages/ae/50/64c94cfc4db8d9ed07da71427a936b5a2bd2b27c66269b42fbda82c7c7a4/grpcio-1.70.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading grpcio-1.70.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting markdown>=2.6.8 (from tensorboard)
  Obtaining dependency information for markdown>=2.6.8 from https://files.pythonhosted.org/packages/3f/08/83871f3c50fc983b88547c196d11cf8c3340e37c32d2e9d6152abe2c61f7/Markdown-3.7-py3-none-any.whl.metadata
  Downloading Markdown-3.7-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: numpy>=1.12.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from tensorboard) (1.26.0)
Requirement already satisfied: packaging in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from tensorboard) (23.2)
Collecting protobuf!=4.24.0,>=3.19.6 (from tensorboard)
  Obtaining dependency information for protobuf!=4.24.0,>=3.19.6 from https://files.pythonhosted.org/packages/a8/45/2ebbde52ad2be18d3675b6bee50e68cd73c9e0654de77d595540b5129df8/protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl.metadata
  Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Requirement already satisfied: six>1.9 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from tensorboard) (1.16.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Obtaining dependency information for tensorboard-data-server<0.8.0,>=0.7.0 from https://files.pythonhosted.org/packages/73/c6/825dab04195756cf8ff2e12698f22513b3db2f64925bdd41671bfb33aaa5/tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Obtaining dependency information for werkzeug>=1.0.1 from https://files.pythonhosted.org/packages/52/24/ab44c871b0f07f491e5d2ad12c9bd7358e527510618cb1b803a88e986db1/werkzeug-3.1.3-py3-none-any.whl.metadata
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from werkzeug>=1.0.1->tensorboard) (2.1.3)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.4.1)
  Obtaining dependency information for mpmath<1.4,>=1.1.0 from https://files.pythonhosted.org/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl.metadata
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading torch-2.4.1-cp312-cp312-manylinux1_x86_64.whl (797.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.0/797.0 MB 1.1 MB/s eta 0:00:0000:0100:04
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.2 MB/s eta 0:00:0000:0100:03
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Downloading nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 2.1 MB/s eta 0:00:0000:0100:01
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Downloading triton-3.0.0-1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (209.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 MB 2.1 MB/s eta 0:00:0000:0100:01
Downloading tensorboard-2.19.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 7.0 MB/s eta 0:00:0000:0100:01
Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 4.7 MB/s eta 0:00:00
Downloading grpcio-1.70.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 6.1 MB/s eta 0:00:0000:0100:01
Downloading Markdown-3.7-py3-none-any.whl (106 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 4.4 MB/s eta 0:00:00
Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.7/319.7 kB 7.7 MB/s eta 0:00:00a 0:00:01
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 5.9 MB/s eta 0:00:0000:0100:01m
Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 11.2 MB/s eta 0:00:00
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.7 MB/s eta 0:00:0000:0100:01m
Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 5.3 MB/s eta 0:00:0000:0100:01m
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Downloading nvidia_nvjitlink_cu12-12.8.61-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.2/39.2 MB 5.4 MB/s eta 0:00:0000:0100:01
Installing collected packages: mpmath, werkzeug, triton, tensorboard-data-server, sympy, protobuf, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, networkx, markdown, grpcio, absl-py, tensorboard, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, torch
Successfully installed absl-py-2.1.0 grpcio-1.70.0 markdown-3.7 mpmath-1.3.0 networkx-3.4.2 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.8.61 nvidia-nvtx-cu12-12.1.105 protobuf-5.29.3 sympy-1.13.3 tensorboard-2.19.0 tensorboard-data-server-0.7.2 torch-2.4.1 triton-3.0.0 werkzeug-3.1.3
Note: you may need to restart the kernel to use updated packages.
Collecting flash-attn
  Downloading flash_attn-2.7.4.post1.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 5.9 MB/s eta 0:00:0000:0100:01m
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools<71.0.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (68.0.0)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/29/7a/8bce8968883e9465de20be15542f4c7e221952441727c4dad24d534c6d99/scikit_learn-1.6.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading scikit_learn-1.6.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: torch in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from flash-attn) (2.4.1)
Collecting einops (from flash-attn)
  Obtaining dependency information for einops from https://files.pythonhosted.org/packages/87/62/9773de14fe6c45c23649e98b83231fffd7b9892b6cf863251dc2afa73643/einops-0.8.1-py3-none-any.whl.metadata
  Downloading einops-0.8.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from scikit-learn) (1.26.0)
Collecting scipy>=1.6.0 (from scikit-learn)
  Obtaining dependency information for scipy>=1.6.0 from https://files.pythonhosted.org/packages/c0/53/eaada1a414c026673eb983f8b4a55fe5eb172725d33d62c1b21f63ff6ca4/scipy-1.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading scipy-1.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 5.2 MB/s eta 0:00:00
Collecting joblib>=1.2.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.2.0 from https://files.pythonhosted.org/packages/91/29/df4b9b42f2be0b623cbd5e2140cafcaa2bef0759a00b7b70104dcfe2fb51/joblib-1.4.2-py3-none-any.whl.metadata
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=3.1.0 from https://files.pythonhosted.org/packages/4b/2c/ffbf7a134b9ab11a67b0cf0726453cedd9c5043a4fe7a35d1cefa9a1bcfb/threadpoolctl-3.5.0-py3-none-any.whl.metadata
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (3.12.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (4.8.0)
Requirement already satisfied: sympy in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (1.13.3)
Requirement already satisfied: networkx in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (3.4.2)
Requirement already satisfied: jinja2 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (3.1.2)
Requirement already satisfied: fsspec in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (2023.9.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from torch->flash-attn) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->flash-attn) (12.8.61)

In [1]:
from datasets import load_dataset
 
# Dataset id from huggingface.co/dataset
dataset_id = "youralien/feedback_qesconv_16wayclassification"
 
# Load raw dataset
raw_dataset = load_dataset(dataset_id, split="train") # happens to be called train

print(f"Raw dataset size: {len(raw_dataset)}")

/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Generating train split: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8179/8179 [00:00<00:00, 14844.19 examples/s]

Raw dataset size: 8179

In [2]:
split_dataset = raw_dataset.train_test_split(test_size=0.1)
print(f"Train dataset size: {len(split_dataset['train'])}")
print(f"Test dataset size: {len(split_dataset['test'])}")
split_dataset['train'][0]

Train dataset size: 7361
Test dataset size: 818

{'conv_index': 194,
 'helper_index': 8,
 'input': ["Helper: I see. That's a very important role for any business. I bet there are numerous other retailers out there looking for a good manager to hire.",
  'Seeker: That is true, I am just not sure if that is what I want to do anymore',
  'Helper: I see. Well then, if this helps. The store closing might have been a positive thing, so you could find your next passion.',
  'Seeker: That is a good point.',
  'Helper: I will also add, that being a Manager means you have some very important skills that would translate well to your next job, or anything you decide to do.',
  "Seeker: That's true. I know the experience will help me but I still miss it",
  "Helper: Also, let's say you decided to work for another company, something new, outside of retail. Because you were a manager, you could also be promoted more quickly because of your management experience.",
  'Seeker: That is also true. I guess I just need to decide what I want to do now. That is probably the most difficult part.',
  'Helper: Yes, it sounds like a part of you still misses the retail environment. I see that too. My best advice, is take a few days to think about what you really want to do. Think about what you are skilled at. Then decide which route you want to go. I know there will be numerous options out there for you in retail management, but if you wanted to do something different, there will be opportunities there too. Because you have options, you will likely pick the choice that will be most fulfilling for you, in something you will be passionate about - so this will likely be very positive for you.',
  'Seeker: That is really nice to say. I guess I am also just scared to go for something and have it not be as fulfilling as I thought',
  "Helper: It's understandable that you're feeling scared about making a decision and not finding it fulfilling. It's a big decision and it's okay to take time and consider your options carefully."],
 'Reflections-goodareas': 0,
 'Validation-goodareas': 1,
 'Empathy-goodareas': 1,
 'Questions-goodareas': 0,
 'Suggestions-goodareas': 0,
 'Self-disclosure-goodareas': 0,
 'Structure-goodareas': 0,
 'Professionalism-goodareas': 0,
 'Reflections-badareas': 0,
 'Validation-badareas': 0,
 'Empathy-badareas': 0,
 'Questions-badareas': 0,
 'Suggestions-badareas': 0,
 'Self-disclosure-badareas': 0,
 'Structure-badareas': 0,
 'Professionalism-badareas': 0}

In [170]:
def prepare_input_text(example):
    # Convert the last two items of input list to a single text
    return {
        'text': "\n".join(example['input'][-2:]),
        **{k:v for k,v in example.items() if k != 'input'}  # Keep other fields
    }

# Apply the preprocessing
split_dataset = split_dataset.map(prepare_input_text)
split_dataset['train'][0]

Map: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7361/7361 [00:01<00:00, 5568.36 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 818/818 [00:00<00:00, 5429.85 examples/s]

{'conv_index': 216,
 'helper_index': 1,
 'input': ['Helper: hi! Hope you are doing well today. How may I assist you ?',
  'Seeker: Hey! I’ve been better. Just so stressed out! I don’t handle pressure well.',
  "Helper: I'm sorry to hear you're feeling stressed. Can you tell me more about what's causing this pressure?"],
 'Reflections-goodareas': 1,
 'Validation-goodareas': 0,
 'Empathy-goodareas': 0,
 'labels': 1,
 'Suggestions-goodareas': 0,
 'Self-disclosure-goodareas': 0,
 'Structure-goodareas': 0,
 'Professionalism-goodareas': 0,
 'Reflections-badareas': 0,
 'Validation-badareas': 0,
 'Empathy-badareas': 0,
 'Questions-badareas': 0,
 'Suggestions-badareas': 0,
 'Self-disclosure-badareas': 0,
 'Structure-badareas': 0,
 'Professionalism-badareas': 0,
 'text': "Seeker: Hey! I’ve been better. Just so stressed out! I don’t handle pressure well.\nHelper: I'm sorry to hear you're feeling stressed. Can you tell me more about what's causing this pressure?"}

In [171]:
from transformers import AutoTokenizer
 
# Model id to load the tokenizer
model_id = "answerdotai/ModernBERT-large"
# model_id = "answerdotai/ModernBERT-base"
# model_id = "google-bert/bert-base-uncased"

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.model_max_length = 512 # set model_max_length to 512 as prompts are not longer than 1024 tokens
 
# Tokenize helper 
 
# Tokenize helper function
def tokenize(batch):
    # return tokenizer(batch['text'], padding=True, truncation=True, return_tensors="pt")
    return tokenizer(batch['text'], padding='max_length', truncation=True, return_tensors="pt")


which_class = "Reflections-goodareas"
SKILL_OPTIONS = ["Reflections", "Validation", "Empathy", "Questions", "Suggestions", "Self-disclosure", "Structure", "Professionalism"]
goodareas_to_ignore = [f"{skill}-goodareas" for skill in SKILL_OPTIONS if f"{skill}-goodareas" != which_class]
badareas_to_ignore = [f"{skill}-badareas" for skill in SKILL_OPTIONS if f"{skill}-badareas" != which_class]
cols_to_remove = ['conv_index', 'helper_index', 'input', 'text']
cols_to_remove.extend(goodareas_to_ignore)
cols_to_remove.extend(badareas_to_ignore)
if which_class in split_dataset["train"].features.keys():
    split_dataset =  split_dataset.rename_column(which_class, "labels") # to match Trainer
tokenized_dataset = split_dataset.map(tokenize, batched=True, remove_columns=cols_to_remove)
 
tokenized_dataset["train"].features.keys()
# dict_keys(['labels', 'input_ids', 'attention_mask'])

ValueError: New column name labels already in the dataset. Please choose a column name which is not already in the dataset. Current columns in the dataset: ['conv_index', 'helper_index', 'input', 'Reflections-goodareas', 'Validation-goodareas', 'Empathy-goodareas', 'labels', 'Suggestions-goodareas', 'Self-disclosure-goodareas', 'Structure-goodareas', 'Professionalism-goodareas', 'Reflections-badareas', 'Validation-badareas', 'Empathy-badareas', 'Questions-badareas', 'Suggestions-badareas', 'Self-disclosure-badareas', 'Structure-badareas', 'Professionalism-badareas', 'text']

In [148]:
from transformers import AutoModelForSequenceClassification
 
# Prepare model labels - useful for inference
labels = ["not selected", "selected"]
num_labels = len(labels)
label2id, id2label = dict(), dict()
for i, label in enumerate(labels):
    label2id[label] = str(i)
    id2label[str(i)] = label
 
# Download the model from huggingface.co/models
model = AutoModelForSequenceClassification.from_pretrained(
    model_id, num_labels=num_labels, label2id=label2id, id2label=id2label,
)

Some weights of ModernBertForSequenceClassification were not initialized from the model checkpoint at answerdotai/ModernBERT-large and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [149]:
import evaluate
import numpy as np

def compute_metrics_fn(eval_preds):
    metrics = dict()
    
    accuracy_metric = evaluate.load('accuracy')
    precision_metric = evaluate.load('precision')
    recall_metric = evaluate.load('recall')
    f1_metric = evaluate.load('f1')
    
    logits = eval_preds.predictions
    labels = eval_preds.label_ids
    preds = np.argmax(logits, axis=-1)  
    
    metrics.update(accuracy_metric.compute(predictions=preds, references=labels))
    metrics.update(precision_metric.compute(predictions=preds, references=labels, average='binary'))
    metrics.update(recall_metric.compute(predictions=preds, references=labels, average='binary'))
    metrics.update(f1_metric.compute(predictions=preds, references=labels, average='binary'))
    
    return metrics

In [150]:
class_distribution = split_dataset['train'].select_columns(['labels']).to_pandas().value_counts()
print("Class distribution:")
class_distribution = class_distribution / len(split_dataset['train'])
print(class_distribution)
inverse_weights = 1 / class_distribution
inverse_weights = inverse_weights.astype('float32')
inverse_weights.values

# https://github.com/richardaecn/class-balanced-loss/blob/master/src/cifar_main.py#L425-L430
# https://openaccess.thecvf.com/content_CVPR_2019/papers/Cui_Class-Balanced_Loss_Based_on_Effective_Number_of_Samples_CVPR_2019_paper.pdf#page=4.43
# hyperparameter sweep: {softmax, sigmoid, focal} for loss type, β ∈ {0.9, 0.99, 0.999, 0.9999} (Section 4), and γ ∈ {0.5, 1.0, 2.0} for focal loss [27].
# img_num_per_cls = data_utils.get_img_num_per_cls(
#     hparams['data_version'], hparams['imb_factor'])
# effective_num = 1.0 - np.power(hparams['beta'], img_num_per_cls)
# weights = (1.0 - hparams['beta']) / np.array(effective_num)
# weights = weights / np.sum(weights) * int(hparams['data_version'])

Class distribution:
labels
0         0.757642
1         0.242358
Name: count, dtype: float64

array([1.3198853, 4.126121 ], dtype=float32)

In [152]:
from huggingface_hub import HfFolder
from transformers import Trainer, TrainingArguments

import torch

def compute_class_balanced_loss(outputs, labels, num_items_in_batch):
    """depends on the class_distribution variable defined above"""
    logits = outputs['logits']
    criterion = torch.nn.CrossEntropyLoss(weight=torch.tensor(inverse_weights.values, device=0))
    loss = criterion(logits, labels)
    return loss

# Define training args
training_args = TrainingArguments(
    output_dir= f"ModernBERT-{which_class}-classifier",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=7e-5, # originally 5e-5
    num_train_epochs=5, # suggestion by claude to reduce
    # weight_decay=0.01, # suggestion by claude to reduce
    bf16=True, # bfloat16 training 
    optim="adamw_torch_fused", # improved optimizer 
    # logging & evaluation strategies
    logging_strategy="steps",
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    # use_mps_device=True, # mps device is a mac thing
    metric_for_best_model="f1",
    # push to hub parameters
    report_to="tensorboard",
    push_to_hub=True,
    hub_strategy="every_save",
    hub_token=HfFolder.get_token(),
)
 
 
# Create a Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics_fn,
    compute_loss_func=compute_class_balanced_loss, # custom class balanced loss
)

trainer.train()
# {'train_runtime': 3642.7783, 'train_samples_per_second': 1.235, 'train_steps_per_second': 0.04, 'train_loss': 0.535627057634551, 'epoch': 5.0}

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

TrainOutput(global_step=2305, training_loss=0.27855713936356813, metrics={'train_runtime': 598.1122, 'train_samples_per_second': 61.535, 'train_steps_per_second': 3.854, 'total_flos': 3.892334898514944e+16, 'train_loss': 0.27855713936356813, 'epoch': 5.0})

In [167]:
# Save processor and create model card
tokenizer.save_pretrained(f"ModernBERT-{which_class}-classifier")
trainer.create_model_card()
trainer.push_to_hub()

KeyboardInterrupt:

## Exploring Hyperparameter Sweeps with WanDB
Link: https://wandb.ai/matt24/vit-snacks-sweeps/reports/Hyperparameter-Search-for-HuggingFace-Transformer-Models--VmlldzoyMTUxNTg0

In [13]:
# %pip install -qq wandb --upgrade
%pip install evaluate

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting evaluate
  Obtaining dependency information for evaluate from https://files.pythonhosted.org/packages/a2/e7/cbca9e2d2590eb9b5aa8f7ebabe1beb1498f9462d2ecede5c9fd9735faaf/evaluate-0.4.3-py3-none-any.whl.metadata
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: datasets>=2.0.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (3.1.0)
Requirement already satisfied: numpy>=1.17 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (1.26.0)
Requirement already satisfied: dill in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (2.2.3)
Requirement already satisfied: requests>=2.19.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (2023.9.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (0.28.1)
Requirement already satisfied: packaging in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from evaluate) (23.2)
Requirement already satisfied: filelock in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (3.12.4)
Requirement already satisfied: pyarrow>=15.0.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (19.0.1)
Requirement already satisfied: aiohttp in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (3.11.12)
Requirement already satisfied: pyyaml>=5.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from datasets>=2.0.0->evaluate) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from requests>=2.19.0->evaluate) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from requests>=2.19.0->evaluate) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from requests>=2.19.0->evaluate) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from requests>=2.19.0->evaluate) (2023.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.16.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 10.7 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3
Note: you may need to restart the kernel to use updated packages.

In [18]:
import wandb
wandb.login()

%env WANDB_PROJECT=ModernBert_SkillClassifier
%env WANDB_LOG_MODEL=checkpoint

env: WANDB_PROJECT=ModernBert_SkillClassifier
env: WANDB_LOG_MODEL=checkpoint

In [9]:
# method
sweep_config = {
    'method': 'random'
}


# hyperparameters
parameters_dict = {
    'epochs': {
        'value': 1
        },
    'batch_size': {
        'values': [8, 16, 32, 64]
        },
    'learning_rate': {
        'distribution': 'log_uniform_values',
        'min': 1e-5,
        'max': 1e-3
    },
    'weight_decay': {
        'values': [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
    },
}


sweep_config['parameters'] = parameters_dict

In [20]:
sweep_id = wandb.sweep(sweep_config, project=f'modernbert-{which_class}-sweeps')

Create sweep with ID: np9rpy0r
Sweep URL: https://wandb.ai/ryanlouie2021-stanford-university/modernbert-Reflections-goodareas-sweeps/sweeps/np9rpy0r

In [15]:
from transformers import Trainer, TrainingArguments
import torch

def compute_class_balanced_loss(outputs, labels, num_items_in_batch):
    """depends on the class_distribution variable defined above"""
    logits = outputs['logits']
    criterion = torch.nn.CrossEntropyLoss(weight=torch.tensor(inverse_weights.values, device=0))
    loss = criterion(logits, labels)
    return loss

def train(config=None):
    with wandb.init(config=config):
        # set sweep configuration
        config = wandb.config

        # Define training args
        training_args = TrainingArguments(
            output_dir= f"ModernBERT-{which_class}-classifier-sweeps",
            per_device_train_batch_size=config.batch_size,
            per_device_eval_batch_size=16,
            learning_rate=config.learning_rate,
            num_train_epochs=config.epochs,
            weight_decay=config.weight_decay,
            bf16=True, # bfloat16 training 
            optim="adamw_torch_fused", # improved optimizer 
            # logging & evaluation strategies
            logging_strategy="epoch",
            logging_steps=100,
            eval_strategy="epoch",
            save_strategy="epoch",
            save_total_limit=2,
            load_best_model_at_end=True,
            # use_mps_device=True, # mps device is a mac thing
            # push to hub parameters
            report_to="wandb",
            # push_to_hub=True,
            # hub_strategy="every_save",
            # hub_token=HfFolder.get_token(),
        )

        if config.use_class_balanced_loss:
            # Create a Trainer instance
            trainer = Trainer(
                model=model,
                args=training_args,
                train_dataset=tokenized_dataset["train"],
                eval_dataset=tokenized_dataset["test"],
                compute_metrics=compute_metrics_fn,
                compute_loss_func=compute_class_balanced_loss, # custom class balanced loss
            )
        else:
            trainer = Trainer(
                model=model,
                args=training_args,
                train_dataset=tokenized_dataset["train"],
                eval_dataset=tokenized_dataset["test"],
                compute_metrics=compute_metrics_fn,
            )

        trainer.train()

In [21]:
wandb.agent(sweep_id, train, count=20)

wandb: Agent Starting Run: 3u6o9mcs with config:
wandb: 	batch_size: 16
wandb: 	epochs: 1
wandb: 	learning_rate: 7.355714375771006e-05
wandb: 	weight_decay: 0.2
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-461)... Done. 31.0s
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.20k/4.20k [00:00<00:00, 9.22MB/s]
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.56k/7.56k [00:00<00:00, 8.35MB/s]
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.38k/7.38k [00:00<00:00, 7.00MB/s]
Downloading builder script: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.79k/6.79k [00:00<00:00, 15.1MB/s]
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-461)... Done. 37.8s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: ver7zql6 with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 7.867479695440483e-05
wandb: 	weight_decay: 0.1
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116)... Done. 31.4s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116)... Done. 43.8s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: bgkconer with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 0.000670388557945428
wandb: 	weight_decay: 0.5
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116)... Done. 36.7s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116)... Done. 39.2s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: ginadzp8 with config:
wandb: 	batch_size: 32
wandb: 	epochs: 1
wandb: 	learning_rate: 2.100716082070221e-05
wandb: 	weight_decay: 0.4
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231)... Done. 37.1s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231)... Done. 46.1s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 6ofwzhfk with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 7.225029386316786e-05
wandb: 	weight_decay: 0.4
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

Run 6ofwzhfk errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

wandb: ERROR Run 6ofwzhfk errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116
wandb: ERROR
wandb: Agent Starting Run: bfld45b3 with config:
wandb: 	batch_size: 32
wandb: 	epochs: 1
wandb: 	learning_rate: 5.914033848973156e-05
wandb: 	weight_decay: 0.1
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231)... Done. 38.1s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231)... Done. 37.3s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: mjq9j1y2 with config:
wandb: 	batch_size: 8
wandb: 	epochs: 1
wandb: 	learning_rate: 1.0912522642694691e-05
wandb: 	weight_decay: 0.1
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-921)... Done. 31.0s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-921)... Done. 47.2s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: ppaajpfs with config:
wandb: 	batch_size: 8
wandb: 	epochs: 1
wandb: 	learning_rate: 0.0005960618618120046
wandb: 	weight_decay: 0
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-921)... Done. 43.9s
/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-921)... Done. 43.6s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: f4splclm with config:
wandb: 	batch_size: 16
wandb: 	epochs: 1
wandb: 	learning_rate: 1.5273955879633985e-05
wandb: 	weight_decay: 0.2
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-461)... Done. 38.0s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-461)... Done. 39.3s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: 0iqpwizp with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 4.1017160589087415e-05
wandb: 	weight_decay: 0
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

Run 0iqpwizp errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

wandb: ERROR Run 0iqpwizp errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116
wandb: ERROR
wandb: Agent Starting Run: re0dfpi3 with config:
wandb: 	batch_size: 8
wandb: 	epochs: 1
wandb: 	learning_rate: 0.0002053295617741895
wandb: 	weight_decay: 0.2
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-921)... Done. 40.8s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-921)... Done. 40.7s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: 1qnrtp6c with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 3.0818986233971844e-05
wandb: 	weight_decay: 0.3
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

Run 1qnrtp6c errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

wandb: ERROR Run 1qnrtp6c errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116
wandb: ERROR
wandb: Agent Starting Run: vhi1pheu with config:
wandb: 	batch_size: 32
wandb: 	epochs: 1
wandb: 	learning_rate: 0.0001076727013655306
wandb: 	weight_decay: 0.3
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

Run vhi1pheu errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

wandb: ERROR Run vhi1pheu errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231
wandb: ERROR
wandb: Agent Starting Run: a6s13itb with config:
wandb: 	batch_size: 32
wandb: 	epochs: 1
wandb: 	learning_rate: 0.0001376756358546193
wandb: 	weight_decay: 0.1
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

Run a6s13itb errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

wandb: ERROR Run a6s13itb errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231
wandb: ERROR
wandb: Agent Starting Run: pxufas3e with config:
wandb: 	batch_size: 16
wandb: 	epochs: 1
wandb: 	learning_rate: 0.00038069941025126104
wandb: 	weight_decay: 0
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-461)... Done. 37.3s
wandb: Adding directory to artifact (./ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-461)... Done. 40.9s
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

wandb: Agent Starting Run: hgqk1sp5 with config:
wandb: 	batch_size: 32
wandb: 	epochs: 1
wandb: 	learning_rate: 1.8232626131087615e-05
wandb: 	weight_decay: 0.4
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

Run hgqk1sp5 errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

wandb: ERROR Run hgqk1sp5 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231
wandb: ERROR
wandb: Agent Starting Run: hutjz5n2 with config:
wandb: 	batch_size: 32
wandb: 	epochs: 1
wandb: 	learning_rate: 5.251685231407168e-05
wandb: 	weight_decay: 0.4
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

Run hutjz5n2 errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231

wandb: ERROR Run hutjz5n2 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-231
wandb: ERROR
wandb: Agent Starting Run: rd0hak7n with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 0.00013992391944721335
wandb: 	weight_decay: 0.3
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

Run rd0hak7n errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

wandb: ERROR Run rd0hak7n errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116
wandb: ERROR
wandb: Agent Starting Run: 0g9pz5x1 with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 1.603188107757382e-05
wandb: 	weight_decay: 0.4
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

Run 0g9pz5x1 errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

wandb: ERROR Run 0g9pz5x1 errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116
wandb: ERROR
wandb: Agent Starting Run: noplgwdw with config:
wandb: 	batch_size: 64
wandb: 	epochs: 1
wandb: 	learning_rate: 3.0396199138075233e-05
wandb: 	weight_decay: 0.1
Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).

Traceback (most recent call last):
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

Run noplgwdw errored:
Traceback (most recent call last):
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
    self._function()
  File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
    trainer.train()
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
    self.control = self.callback_handler.on_save(self.args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
    return self.call_event("on_save", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
    artifact.add_dir(artifact_path)
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
    raise ValueError("Path is not a directory: {}".format(local_path))
ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116

wandb: ERROR Run noplgwdw errored:
wandb: ERROR Traceback (most recent call last):
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/agents/pyagent.py", line 306, in _run_job
wandb: ERROR     self._function()
wandb: ERROR   File "/tmp/rylouie/ipykernel_2378267/119082754.py", line 51, in train
wandb: ERROR     trainer.train()
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2163, in train
wandb: ERROR     return inner_training_loop(
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 2590, in _inner_training_loop
wandb: ERROR     self._maybe_log_save_evaluate(
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer.py", line 3071, in _maybe_log_save_evaluate
wandb: ERROR     self.control = self.callback_handler.on_save(self.args, self.state, self.control)
wandb: ERROR                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 508, in on_save
wandb: ERROR     return self.call_event("on_save", args, state, control)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/trainer_callback.py", line 519, in call_event
wandb: ERROR     result = getattr(callback, event)(
wandb: ERROR              ^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/transformers/integrations/integration_utils.py", line 990, in on_save
wandb: ERROR     artifact.add_dir(artifact_path)
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/_validators.py", line 115, in wrapper
wandb: ERROR     return method(self, *args, **kwargs)
wandb: ERROR            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
wandb: ERROR   File "/nlp/scr/rylouie/miniconda3/envs/llama/lib/python3.12/site-packages/wandb/sdk/artifacts/artifact.py", line 1347, in add_dir
wandb: ERROR     raise ValueError("Path is not a directory: {}".format(local_path))
wandb: ERROR ValueError: Path is not a directory: ModernBERT-Reflections-goodareas-classifier-sweeps/checkpoint-116
wandb: ERROR

## Using the model to make predictions

In [186]:
import pandas as pd


condition = "control"
# condition = "treatment"
# input_data = pd.read_csv(f"../Empathy-Mental-Health/dataset/all_{condition}_seekerhelper_pairs.csv")
input_data = pd.read_csv("N94_all_seekerhelper_pairs.csv")
print(len(input_data))
input_data.head()

3842

,id,seeker_post,response_post
0,14_a1df3c7155d0438b9c4084b57b66c6e6_0_0,NaN,good evening I understand you're feeling isola...
1,14_a1df3c7155d0438b9c4084b57b66c6e6_0_1,"Yeah, it's just... everyone was with their fam...",I hear you. It can be difficult growing apart ...
2,14_a1df3c7155d0438b9c4084b57b66c6e6_0_2,"Yeah, it's tough. You know, during the holiday...",Perhaps they're feeling similarly. Waiting for...
3,14_a1df3c7155d0438b9c4084b57b66c6e6_0_3,But why should I always have to be the bigger ...,"Being the bigger person can feel burdensome, c..."
4,14_a1df3c7155d0438b9c4084b57b66c6e6_0_4,"Yeah, exactly. It's like, why should I keep pu...",How would you like for them to show you they c...

In [187]:
from transformers import pipeline
 
# load model from huggingface.co/models using our repository id
classifier = pipeline("sentiment-analysis", model=f"ModernBERT-{which_class}-classifier", device=0)
# classifier = pipeline("sentiment-analysis", model="ModernBERT-Empathy-goodareas-classifier", device=0)

# sample = f"Seeker: {input_data.loc[0, "seeker_post"]}\nHelper: {input_data.loc[0, "response_post"]}"
# pred = classifier(sample)
# print(pred)

def binary_prediction_seeker_response_post(seeker, helper):
    sample = f"Seeker: {seeker}\nHelper: {helper}"
    pred = classifier(sample)
    return int(pred[0]['label'] == 'selected')

Device set to use cuda:0

In [188]:
# output_preds = input_data.apply(binary_prediction_seeker_response_post, axis=0)

strengths = [binary_prediction_seeker_response_post(input_data.loc[i, "seeker_post"], input_data.loc[i, "response_post"])
             for i in range(len(input_data))]

In [189]:
input_data[f"{which_class}"] = strengths
# input_data["Empathy-goodareas"] = strengths

In [193]:
print(len(input_data))
input_data.head()

3842

,id,seeker_post,response_post,Reflections-goodareas
0,14_a1df3c7155d0438b9c4084b57b66c6e6_0_0,NaN,good evening I understand you're feeling isola...,0
1,14_a1df3c7155d0438b9c4084b57b66c6e6_0_1,"Yeah, it's just... everyone was with their fam...",I hear you. It can be difficult growing apart ...,1
2,14_a1df3c7155d0438b9c4084b57b66c6e6_0_2,"Yeah, it's tough. You know, during the holiday...",Perhaps they're feeling similarly. Waiting for...,0
3,14_a1df3c7155d0438b9c4084b57b66c6e6_0_3,But why should I always have to be the bigger ...,"Being the bigger person can feel burdensome, c...",0
4,14_a1df3c7155d0438b9c4084b57b66c6e6_0_4,"Yeah, exactly. It's like, why should I keep pu...",How would you like for them to show you they c...,0

In [195]:
# input_data.to_csv(f'all_{condition}_seekerhelper_pairs_{which_class}.csv')
input_data.to_csv(f"N94_all_seekerhelper_pairs_{which_class}.csv")

In [192]:
f'all_{condition}_seekerhelper_pairs_{which_class}.csv'

'all_control_seekerhelper_pairs_Reflections-goodareas.csv'